/**
 * Eukolia — Mathematical Symbols: the contracts.
 *
 * This module is the vocabulary the rest of the feature is written in. It has no
 * imports, so the catalog, the search index, the project snapshot, the resolver,
 * the inserter and the panel can all agree on these shapes without any of them
 * depending on the others — and so the pure parts can be tested without a DOM,
 * an editor, MathJax or Electron.
 *
 * Three groups of types live here:
 *
 *  1. **The catalog** (`MathSymbolEntry` and below) — static data, generated by
 *     `scripts/generate-math-symbol-catalog.mjs` and never edited by hand. A
 *     catalog entry says what a symbol *is*; it deliberately says nothing about
 *     whether this project can typeset it.
 *  2. **The project snapshot** (`ProjectSymbolSnapshot`) — what the workspace
 *     analysis knows right now: the compilation root, the macros in scope, the
 *     packages loaded, the engine. It carries a revision so a stale result can
 *     be recognised as stale instead of being applied.
 *  3. **The insertion plan** (`InsertionPlan`) — the whole result of resolving a
 *     symbol at a position: the exact text, where the slots go, where the caret
 *     ends up, and why. An insertion is *planned* as data and then applied in one
 *     transaction, so the decision and the edit cannot disagree.
 *
 * Availability is modelled as **three** states rather than a boolean, because
 * "we have not looked" and "we looked and it is not there" are different facts
 * and the panel must not present them the same way:
 *
 *  * `core` — the LaTeX kernel or base mathematics provides it;
 *  * `project` — a package the document already loads provides it;
 *  * `unknown` — the requirement is not verified, or the package list is not
 *    known yet, so Eukolia says so instead of guessing either way.
 */

/* ------------------------------------------------------------------ *
 * Catalog
 * ------------------------------------------------------------------ */

/**
 * The catalog's own classification.
 *
 * `templates` is the only category that is not a kind of mathematics: a
 * structured construct (a fraction, a matrix, an accent) rather than a glyph.
 * The panel's other two groupings — project macros and the favourites/recent
 * lists — are *views* over the catalog rather than tags on a record, so they
 * are not listed here.
 */
export type MathSymbolCategory =
  | 'greek'
  | 'arrows'
  | 'relations'
  | 'binary-operators'
  | 'large-operators'
  | 'functions'
  | 'logic-sets'
  | 'delimiters'
  | 'accents'
  | 'alphabets'
  | 'miscellaneous'
  | 'templates'

/** Every category, in the order the selector shows them. */
export const MATH_SYMBOL_CATEGORIES: readonly MathSymbolCategory[] = [
  'greek',
  'arrows',
  'relations',
  'binary-operators',
  'large-operators',
  'functions',
  'logic-sets',
  'delimiters',
  'accents',
  'alphabets',
  'miscellaneous',
  'templates'
]

/** Where a symbol may be inserted. */
export type MathSymbolMode = 'math-only' | 'text-only' | 'mode-independent'

/** A LaTeX capability a variant needs before it can compile. */
export interface CapabilityRequirement {
  /** A package name, or `core` for the LaTeX kernel and base mathematics. */
  readonly package: string
  readonly kind: 'core' | 'package' | 'engine'
  /**
   * Whether the attribution was reviewed.
   *
   * `false` means "unknown", not "wrong": the catalog keeps the claim visible
   * and the panel shows it as unverified rather than as available.
   */
  readonly verified: boolean
  /** Which reviewed source the claim came from. */
  readonly source: 'mathjax-configuration' | 'unimathsymbols-detail' | 'curated'
}

/**
 * One argument position of a structured template.
 *
 * Slots are structured rather than placeholder markers in a string, so nothing
 * downstream has to parse `#1` out of LaTeX — which is exactly the bug that
 * makes naive symbol palettes mangle `#` inside a macro body.
 */
export interface ArgumentSlot {
  /** 1-based, matching `TemplatePartSlot.slot`. */
  readonly index: number
  readonly required: boolean
  /** What the slot starts as when nothing else fills it. */
  readonly default: string
  /**
   * What is selected once the template is in the document.
   *
   * `selected-text` is the slot a compatible editor selection moves into — the
   * one an accent or a fraction takes its argument from.
   */
  readonly select: 'placeholder' | 'selected-text' | 'none'
  readonly description?: string
}

/** Literal LaTeX in a template body. */
export interface TemplatePartText {
  readonly text: string
}

/** A slot's position in a template body. */
export interface TemplatePartSlot {
  readonly slot: number
}

export type TemplatePart = TemplatePartText | TemplatePartSlot

/**
 * One way of writing a symbol.
 *
 * A symbol may have several: `\le` and `\leq` are two spellings of one
 * relation, and a project alias is a third. The variant is what actually gets
 * inserted, so it is the variant — not the entry — that carries the package
 * requirements and the mode.
 */
export interface SymbolVariant {
  /** Stable across regeneration: `<entryId>@<spelling>`. */
  readonly id: string
  /**
   * The control sequence, with its backslash, or `null` for a variant that is
   * not a single command.
   *
   * A curated constant such as `\mathbb{R}` and a multi-part template such as
   * `\begin{pmatrix}…\end{pmatrix}` are complete expressions rather than
   * commands, so there is no one control sequence to name — and answering with
   * `entry.name` instead would make the display name look like something the
   * user could type. Anything that needs a spelling falls back to the entry's
   * name explicitly.
   */
  readonly command: string | null
  /** The body, with slots expressed as parts rather than as markers. */
  readonly parts: readonly TemplatePart[]
  readonly slots: readonly ArgumentSlot[]
  readonly requires: readonly CapabilityRequirement[]
  /** Engines the variant is restricted to, when the source states one. */
  readonly engines: readonly string[] | null
  readonly mode: MathSymbolMode
  /**
   * Whether the variant brings its own mathematics with it.
   *
   * True for `\ensuremath`, which typesets its argument as mathematics wherever
   * it appears — so it needs no `$…$` wrapper and must not get one.
   */
  readonly selfContainedMath: boolean
}

/** How the grid previews a symbol. */
export type SymbolPreview = 'glyph' | 'command' | 'math'

/** One catalog entry. */
export interface MathSymbolEntry {
  /** Stable semantic id, e.g. `mjs:alpha`, `ums:boxminus`, `tpl:frac`. */
  readonly id: string
  /** The display name, normally the canonical control sequence. */
  readonly name: string
  /** The Unicode glyph, when one draws the symbol faithfully. */
  readonly glyph: string | null
  readonly preview: SymbolPreview
  /** The LaTeX that typesets the preview, for `preview: 'math'`. */
  readonly previewSource: string | null
  readonly categories: readonly MathSymbolCategory[]
  /** Other LaTeX spellings of the same symbol. */
  readonly aliases: readonly string[]
  readonly keywords: readonly string[]
  readonly description: string | null
  /**
   * Verified core availability.
   *
   * `null` means unknown — the entry's requirement was never reviewed — and the
   * panel treats that as unverified rather than as core.
   */
  readonly core: boolean | null
  /** Where the record came from, for the details pane. */
  readonly source: string
  readonly variants: readonly SymbolVariant[]
}

/** The generated catalog file. */
export interface GeneratedCatalog {
  readonly version: number
  readonly categories: readonly string[]
  readonly entries: readonly MathSymbolEntry[]
}

/** One upstream record that produced no catalog entry. */
export interface CatalogExclusion {
  readonly source: 'mathjax' | 'unimathsymbols'
  readonly id: string
  readonly reason: string
}

/**
 * The generator's accounting manifest.
 *
 * The point of the manifest is that "complete" is checkable: every upstream
 * record is emitted, merged, or excluded with a reason, and the generator fails
 * its run when one is none of those.
 */
export interface CatalogManifest {
  readonly version: number
  readonly categories: readonly string[]
  readonly sources: {
    readonly mathjax: {
      readonly package: string
      readonly licence: string
      readonly mapModules: readonly string[]
      readonly maps: readonly string[]
      readonly commands: number
      readonly environments: readonly string[]
    }
    readonly unimathsymbols: {
      readonly path: string
      readonly licence: string
      readonly records: number
      readonly mergedIntoMathJax: number
    }
    readonly curated: {
      readonly templates: number
      readonly extraSymbols: number
      readonly structuralExclusions: number
      readonly variantSpellings: number
    }
  }
  readonly emitted: {
    readonly entries: number
    readonly variants: number
    readonly slots: number
    readonly byCategory: Readonly<Record<string, number>>
  }
  readonly mergedIds: Readonly<Record<string, string>>
  readonly excluded: readonly CatalogExclusion[]
  readonly warnings: readonly string[]
  readonly problems: readonly string[]
}

/* ------------------------------------------------------------------ *
 * Project context
 * ------------------------------------------------------------------ */

/** How a command came to exist, as far as static analysis can tell. */
export type MacroDeclarationKind =
  | 'newcommand'
  | 'renewcommand'
  | 'providecommand'
  | 'def'
  | 'let'
  | 'DeclareMathOperator'
  | 'newenvironment'
  | 'unknown'

/**
 * One macro declaration, with where it came from.
 *
 * `expansion` is the body only when the declaration is a **zero-argument** one
 * whose body is a single token sequence. That is the only case where the body
 * can be read as the macro's meaning; a parameterised body is kept as source
 * and never guessed at.
 */
export interface ProjectMacro {
  /** Without the backslash, the way LaTeX names it. */
  readonly name: string
  readonly kind: MacroDeclarationKind
  readonly args: number
  /** The full source of the declaration. */
  readonly definition: string
  /** A zero-argument body, when the declaration has a readable one. */
  readonly expansion: string | null
  /**
   * The control sequence a `\let` bound the name to, without its backslash.
   *
   * Carried rather than re-derived, because `\let` is the one declaration whose
   * meaning is *not* in its body: `\let\R\mathbb` makes `\R` another name for
   * `\mathbb`, and finding that name by searching the source text is how a
   * reader ends up answering `\R`.
   */
  readonly letTarget?: string | null
  /** Absolute path of the file declaring it, or `null` for an unsaved buffer. */
  readonly file: string | null
  readonly line: number
  /**
   * Whether the declaration is *definitely* in scope at the insertion point.
   *
   * `false` covers everything static analysis cannot prove: a declaration in a
   * file the include graph does not order before the insertion point, a
   * conditional, a repeated inclusion, or a catcode change.
   */
  readonly inScope: boolean
  /** Why the declaration is uncertain, when it is. */
  readonly uncertainty: string | null
}

/** What the project context is allowed to claim, and what it cannot. */
export interface ContextLimitations {
  /** The root the snapshot was built for, or `null` for a standalone file. */
  readonly root: string | null
  /** True when the include graph was truncated by a bound. */
  readonly truncated: boolean
  /** Free-text statements about what was not analysed, shown to the user. */
  readonly notes: readonly string[]
}

/**
 * An immutable, revisioned view of everything the project knows that can
 * change which command should be inserted.
 *
 * Revisions only ever increase, and a consumer that receives a snapshot with a
 * revision older than one it already applied must discard it — that is what
 * keeps a slow analysis from overwriting a newer one.
 */
export interface ProjectSymbolSnapshot {
  /** Monotonically increasing within a session. */
  readonly revision: number
  /** Normalised workspace root, or `null` when nothing is open. */
  readonly workspaceRoot: string | null
  /** The compilation root the macros were resolved against. */
  readonly compilationRoot: string | null
  /** False while analysis is still running; nothing is claimed until it is. */
  readonly complete: boolean
  readonly macros: readonly ProjectMacro[]
  /** Package names the document loads, lower-cased. */
  readonly packages: readonly string[]
  /** The engine the project compiles with, when it is known. */
  readonly engine: string | null
  readonly inclusions: readonly ProjectSymbolInclusion[]
  readonly limitations: ContextLimitations
}

/** One `\input`-family edge in the include graph. */
export interface ProjectSymbolInclusion {
  /** The file doing the including. */
  readonly from: string
  /** The file included, as resolved, or the raw argument when unresolved. */
  readonly to: string
  /** The command that did it: `input`, `include`, `subfile`, `import`, `subimport`. */
  readonly command: string
  readonly depth: number
  /** True when the same target is included again from this position. */
  readonly repeated: boolean
}

/* ------------------------------------------------------------------ *
 * Insertion context
 * ------------------------------------------------------------------ */

/** What the caret's surroundings are. */
export type InsertionContextKind = 'math' | 'text' | 'restricted' | 'unknown'

/** The delimiter family a mathematical region uses. */
export type MathDelimiterKind =
  | 'dollar'
  | 'double-dollar'
  | 'paren'
  | 'bracket'
  | 'environment'
  | 'inner'
  | 'unknown'

/**
 * The classification of one insertion point.
 *
 * `reason` is short and user-facing: when the panel refuses an insertion it says
 * one of these rather than nothing.
 */
export interface InsertionContext {
  readonly kind: InsertionContextKind
  readonly reason: string
  /** The bounds of the enclosing region, when there is one. */
  readonly region: { readonly from: number; readonly to: number } | null
  readonly delimiter: MathDelimiterKind
  /**
   * The offset of the document's opening delimiter for `region`, so a caret that
   * lands before it can be told it is in prose.
   */
  readonly contentFrom: number | null
  readonly contentTo: number | null
  /** Set when the parser had not reached the position and the answer is a guess. */
  readonly parsedTo: number | null
}

/* ------------------------------------------------------------------ *
 * Resolution
 * ------------------------------------------------------------------ */

/** Whether a variant can be used, and why not when it cannot. */
export type AvailabilityStatus = 'core' | 'project' | 'unknown' | 'missing-package'

export interface Availability {
  readonly status: AvailabilityStatus
  /** The package that would satisfy it, when one is named. */
  readonly package: string | null
  /** A short sentence for the details pane. */
  readonly reason: string
  /** False when the requirement was never reviewed. */
  readonly verified: boolean
}

/** Why a candidate was chosen. */
export type CandidateOrigin =
  | 'preferred-variant'
  | 'project-alias'
  | 'canonical'
  | 'equivalent-variant'
  | 'project-macro'
  | 'raw-code'

/** A ranked, resolvable way of inserting a symbol. */
export interface SymbolCandidate {
  readonly entryId: string
  readonly variantId: string
  readonly command: string
  readonly origin: CandidateOrigin
  readonly availability: Availability
  readonly mode: MathSymbolMode
  readonly selfContainedMath: boolean
  /** Where a project alias was declared, when the candidate is one. */
  readonly declaredAt: { readonly file: string | null; readonly line: number } | null
  /**
   * How many arguments a project alias takes, or `null` for a catalog spelling.
   *
   * It decides how the alias is inserted, and the two answers are different
   * constructs. A zero-argument alias *is* the expression — `\R` denotes
   * `\mathbb{R}` whole — so it is inserted as its own name with no slots. A
   * parameterised alias (`\newcommand{\vect}[1]{\mathbf{#1}}`) is another way of
   * writing the catalog command, so it takes the same arguments in the same
   * order and is inserted into the same parts.
   */
  readonly aliasArgCount?: number | null
  /** Extra sentences the details pane shows. */
  readonly notes: readonly string[]
  /** True when normal insertion is refused and only explicit copy is offered. */
  readonly insertable: boolean
}

/* ------------------------------------------------------------------ *
 * Insertion plan
 * ------------------------------------------------------------------ */

/** One text edit, in document coordinates. */
export interface PlannedChange {
  readonly from: number
  readonly to: number
  readonly insert: string
}

/** Where the caret goes, and which slot that is. */
export interface PlannedCaret {
  readonly anchor: number
  readonly head: number
  /** 1-based slot index when the caret lands in one. */
  readonly slot: number | null
}

/** One selection's share of a plan. */
export interface PlannedRange {
  readonly from: number
  readonly to: number
  readonly changes: readonly PlannedChange[]
  readonly caret: PlannedCaret
  /** The wrapping applied, for the panel to state exactly what will be inserted. */
  readonly wrapped: 'none' | 'inline-math'
}

/**
 * A complete insertion: the exact source, the caret, and an explanation.
 *
 * A plan is built from a *pre-transaction* snapshot of the editor state and is
 * applied in one transaction. Nothing is written until the plan validates, so a
 * refusal leaves the document untouched rather than half-edited.
 */
export interface InsertionPlan {
  readonly ok: true
  readonly entryId: string
  readonly variantId: string
  /** The spelling inserted, or `null` for a variant that is a whole expression. */
  readonly command: string | null
  /** The text the panel shows as "this is what will be inserted". */
  readonly preview: string
  readonly changes: readonly PlannedChange[]
  readonly carets: readonly PlannedCaret[]
  readonly ranges: readonly PlannedRange[]
  /** One short sentence describing the classification that was used. */
  readonly explanation: string
}

/** The refusal, which is a result rather than an exception. */
export interface InsertionFailure {
  readonly ok: false
  readonly entryId: string
  readonly code:
    | 'unavailable'
    | 'no-variant'
    | 'restricted-context'
    | 'unknown-context'
    | 'mode-mismatch'
    | 'crosses-boundary'
    | 'no-editor'
    | 'read-only'
    | 'empty-selection-mix'
  readonly message: string
}

export type InsertionResult = InsertionPlan | InsertionFailure
