// @vitest-environment node
/**
 * The scan and the parser must agree.
 *
 * Above `SOURCE_SCAN_LINES` the analysis comes from `latexScan.ts` instead of the
 * unified-latex AST, so the two are *different implementations of one contract*: the
 * outline, the labels, the citations, the includes, the environments and the macro
 * definitions a document yields must not depend on which one ran. Every case here is
 * analysed twice — once through `latexDocumentAnalyzer.analyze` (the parser) and once
 * through `analyzeByScan` — and the two answers are compared field by field.
 *
 * The corpus is deliberately hermetic: no file in it comes from this machine, and the
 * large document is generated by repeating a fragment rather than read from a
 * project. What it cannot cover is a 47 886-line file of real LaTeX; that is what the
 * note at the end of the file records.
 */
import { describe, expect, it } from 'vitest'

import { analyzeByScan, latexDocumentAnalyzer } from '@/parser/latexAnalyzer'
import { SOURCE_SCAN_LINES } from '@/parser/latexScan'
import type { LatexDocumentAnalysis } from '@/parser/latexAnalyzer'

const MAIN = 'C:/project/main.tex'

/** The parser's answer and the scan's answer for one document. */
function both(text: string, uri = MAIN): { parsed: LatexDocumentAnalysis; scanned: LatexDocumentAnalysis } {
  return { parsed: latexDocumentAnalyzer.analyze(text, uri), scanned: analyzeByScan(text, uri) }
}

/** Whitespace-insensitive, so raw slices and re-serialised nodes can be compared. */
const tidy = (value: string): string => value.replace(/\s+/g, ' ').trim()

/** Everything the two paths must agree on exactly. */
function expectSameStructure(parsed: LatexDocumentAnalysis, scanned: LatexDocumentAnalysis): void {
  expect(scanned.sectioning).toEqual(parsed.sectioning)
  expect(scanned.labels).toEqual(parsed.labels)
  expect(scanned.includedFiles).toEqual(parsed.includedFiles)
  expect(scanned.citations.map((entry) => ({ ...entry, keys: [...entry.keys] }))).toEqual(
    parsed.citations.map((entry) => ({ ...entry, keys: [...entry.keys] }))
  )
  expect(scanned.environments).toEqual(parsed.environments)
  expect(scanned.outline).toEqual(parsed.outline)
  expect(scanned.macroDefinitions.map((macro) => ({ name: macro.name, args: macro.args, primitive: macro.primitive, line: macro.line }))).toEqual(
    parsed.macroDefinitions.map((macro) => ({ name: macro.name, args: macro.args, primitive: macro.primitive, line: macro.line }))
  )
  expect(scanned.macroDefinitions.map((macro) => tidy(macro.definition))).toEqual(
    parsed.macroDefinitions.map((macro) => tidy(macro.definition))
  )
}

/** A chapter with one of everything the analysis collects. */
const CHAPTER = [
  '% A chapter, with the shapes real documents use.',
  '\\chapter{Foundations}',
  '\\label{ch:foundations}',
  '',
  '\\input{preamble}',
  '\\input{extra}',
  '\\addbibresource{refs.bib}',
  '',
  '\\section{Introduction}\\label{sec:intro}',
  'Text with \\emph{emphasis}, a \\cite{knuth1984} and \\citep[see][p.~3]{lamport1994}.',
  '',
  '\\begin{theorem}\\label{thm:main}',
  'For every $\\alpha$ there is a $\\beta$.',
  '\\begin{proof}',
  'Immediate. \\label{proof:main}',
  '\\end{proof}',
  '\\end{theorem}',
  '',
  '\\subsection*{An unnumbered aside}',
  'More text. \\cite{a,b,c}',
  '',
  '\\begin{verbatim}',
  '\\section{Not a section} \\label{not:a:label} % not a comment',
  '\\end{verbatim}',
  '',
  '\\newcommand{\\R}{\\mathbb{R}}',
  '\\newcommand{\\half}[2]{\\frac{#1}{#2}}',
  '\\renewcommand{\\vec}[1]{\\mathbf{#1}}',
  '\\providecommand{\\given}{\\mid}',
  '\\DeclareMathOperator{\\Spec}{Spec}',
  '\\DeclarePairedDelimiterX{\\braketzw}[2]{\\langle}{\\rangle}{#1 \\,#2}',
  '\\newenvironment{claim}{\\begin{quote}}{\\end{quote}}',
  '\\def\\triple#1#2#3{#1#2#3}',
  '\\let\\oldR\\R',
  '\\LetLtxMacro{\\savedforall}{\\forall}',
  '',
  '\\section{Second}\\label{sec:second}',
  'A title with maths: \\subsection{The $\\alpha$-\\emph{stable} case}',
  '\\begin{itemize}',
  '\\item one',
  '\\item two',
  '\\end{itemize}',
  ''
].join('\n')

describe('the scan and the parser agree', () => {
  it('on a chapter-shaped document', () => {
    const { parsed, scanned } = both(CHAPTER)

    // Not vacuous: the document really does contain all of these. The citation count
    // is the *parser's* — it does not collect every `\cite`-family command in this
    // fragment — and the point of the assertion is only that the comparison below is
    // between two non-empty answers.
    expect(parsed.sectioning.length).toBeGreaterThanOrEqual(4)
    expect(parsed.labels.length).toBeGreaterThanOrEqual(5)
    expect(parsed.citations.length).toBeGreaterThanOrEqual(2)
    expect(parsed.includedFiles.length).toBeGreaterThanOrEqual(2)
    // `theorem`, `proof` and `itemize`: the verbatim environment is not reported by
    // either path, which is one of the agreements this file exists to hold.
    expect(parsed.environments.length).toBeGreaterThanOrEqual(3)
    expect(parsed.macroDefinitions.length).toBeGreaterThanOrEqual(9)
    expect(parsed.outline.length).toBeGreaterThan(0)

    expectSameStructure(parsed, scanned)
  })

  it('on a document large enough that the application would scan it', () => {
    // The threshold is what makes this test about the shipped behaviour rather than
    // about a function: above it, the scan *is* the analysis.
    const chapterLines = CHAPTER.split('\n').length
    const repeats = Math.ceil((SOURCE_SCAN_LINES + 200) / chapterLines)
    const large = Array.from({ length: repeats }, (_unused, index) =>
      CHAPTER.replace(/\\label\{([^}]*)\}/g, '\\label{$1-r' + index + '}').replace('\\chapter{Foundations}', `\\chapter{Part ${index}}`)
    ).join('\n')

    expect(large.split('\n').length).toBeGreaterThan(SOURCE_SCAN_LINES)

    const parsed = latexDocumentAnalyzer.analyze(large, MAIN)
    const scanned = analyzeByScan(large, MAIN)
    expectSameStructure(parsed, scanned)

    // And the application uses the scan for it: same answer, from `analyze`.
    expect(latexDocumentAnalyzer.analyze(large, MAIN)).toEqual(scanned)
    expect(parsed.sectioning.length).toBeGreaterThan(SOURCE_SCAN_LINES / chapterLines)
  })

  it('on comments, escapes and braces that look like syntax', () => {
    const source = [
      '% \\section{Commented out}',
      '\\section{A \\% sign and \\{braces\\}}',
      '\\label{sec:escapes} % trailing \\label{commented}',
      'Text 50\\% of the time.',
      '\\section*{Starred \\textbf{bold} title}',
      '\\section[Short]{Long $x^2$ title}',
      '\\label{sec:short}',
      '\\begin{verbatim}',
      '\\section{Inside verbatim} 100% sure',
      '\\end{verbatim}',
      '\\begin{lstlisting}',
      '\\label{inside:listing}',
      '\\end{lstlisting}',
      '\\label{sec:after}',
      ''
    ].join('\n')

    const { parsed, scanned } = both(source)
    expect(parsed.sectioning.map((entry) => entry.title)).toEqual([
      'A \\% sign and \\{braces\\}',
      'Starred bold title',
      'Short'
    ])
    expect(parsed.labels.map((entry) => entry.name)).toEqual(['sec:escapes', 'sec:short', 'sec:after'])
    expectSameStructure(parsed, scanned)
  })

  it('on an unclosed document, which a file being typed is', () => {
    /*
     * Half-typed LaTeX is the normal state of a document between two keystrokes, and
     * this is the one case in the file where the two paths deliberately differ. For
     * the truncated `\input{par` the parser reports an include whose path is `{` — an
     * artefact of unifying an unclosed group, not something a user would recognise as
     * part of their document. The scan reports nothing, because an unclosed argument
     * is not an argument. Everything else must still agree.
     */
    const source = ['\\section{Work in progress}\\label{sec:wip}', '\\begin{theorem}', '\\item stray', '\\input{par'].join('\n')
    const { parsed, scanned } = both(source)

    expect(parsed.includedFiles.map((entry) => entry.path)).toEqual(['{'])
    expect(scanned.includedFiles).toEqual([])

    const withoutIncludes = (analysis: LatexDocumentAnalysis) => ({ ...analysis, includedFiles: [] })
    expectSameStructure(withoutIncludes(parsed), withoutIncludes(scanned))
  })

  it('on a document with no structure at all', () => {
    const { parsed, scanned } = both('Just prose, no commands. $x + y$\n')
    expect(parsed.sectioning).toEqual([])
    expectSameStructure(parsed, scanned)
  })

  it('on an empty document', () => {
    expectSameStructure(latexDocumentAnalyzer.analyze('', MAIN), analyzeByScan('', MAIN))
  })
})
